from __future__ import annotations

DISH_TERMS: dict[str, list[str]] = {
    "mac and cheese": ["mac and cheese", "macaroni and cheese", "mac & cheese"],
    "hamburger": ["hamburger", "burger", "cheeseburger"],
    "pizza": ["pizza", "pizza bianca"],
    "pasta": ["pasta", "spaghetti", "penne", "rigatoni", "macaroni", "noodles"],
    "salad": ["salad"],
    "soup": ["soup", "stew", "chowder"],
    "stew": ["stew"],
    "risotto": ["risotto"],
    "omelet": ["omelet", "omelette"],
    "sandwich": ["sandwich", "panini"],
}

MEAT_TERMS: dict[str, list[str]] = {
    "beef": ["beef", "steak", "brisket", "short rib", "ground beef"],
    "pork": ["pork", "pork chop", "pork shoulder", "pork belly", "ham"],
    "bacon": ["bacon"],
    "ham": ["ham"],
    "sausage": ["sausage", "chorizo", "pancetta", "prosciutto", "salami"],
    "chicken": ["chicken", "chicken breast", "chicken thigh"],
    "turkey": ["turkey"],
    "lamb": ["lamb"],
    "veal": ["veal"],
    "duck": ["duck"],
    "goose": ["goose"],
    "venison": ["venison"],
    "fish": ["fish", "salmon", "tuna", "cod", "trout", "halibut", "tilapia"],
    "shrimp": ["shrimp", "prawn"],
    "crab": ["crab"],
    "lobster": ["lobster"],
    "shellfish": ["shellfish"],
}

VEGETABLE_TERMS: dict[str, list[str]] = {
    "onion": ["onion", "onions"],
    "garlic": ["garlic"],
    "shallot": ["shallot", "shallots"],
    "scallion": ["scallion", "scallions", "green onion", "green onions"],
    "leek": ["leek", "leeks"],
    "carrot": ["carrot", "carrots"],
    "celery": ["celery"],
    "potato": ["potato", "potatoes"],
    "sweet potato": ["sweet potato", "sweet potatoes"],
    "tomato": ["tomato", "tomatoes"],
    "pepper": ["pepper", "peppers"],
    "bell pepper": ["bell pepper", "bell peppers"],
    "jalapeno": ["jalapeno", "jalapenos"],
    "zucchini": ["zucchini"],
    "squash": ["squash"],
    "broccoli": ["broccoli"],
    "cauliflower": ["cauliflower"],
    "spinach": ["spinach"],
    "kale": ["kale"],
    "cabbage": ["cabbage"],
    "lettuce": ["lettuce"],
    "mushroom": ["mushroom", "mushrooms"],
    "corn": ["corn"],
    "peas": ["pea", "peas"],
    "green bean": ["green bean", "green beans", "string bean", "string beans"],
    "asparagus": ["asparagus"],
    "eggplant": ["eggplant"],
    "cucumber": ["cucumber", "cucumbers"],
    "radish": ["radish", "radishes"],
    "beet": ["beet", "beets"],
    "turnip": ["turnip", "turnips"],
}

HERB_TERMS: dict[str, list[str]] = {
    "basil": ["basil"],
    "parsley": ["parsley"],
    "cilantro": ["cilantro", "coriander leaf"],
    "mint": ["mint"],
    "dill": ["dill"],
    "thyme": ["thyme"],
    "rosemary": ["rosemary"],
    "oregano": ["oregano"],
    "sage": ["sage"],
    "chives": ["chive", "chives"],
    "bay leaf": ["bay leaf", "bay leaves"],
    "tarragon": ["tarragon"],
}

SPICE_TERMS: dict[str, list[str]] = {
    "salt": ["salt", "kosher salt", "table salt", "sea salt"],
    "black pepper": ["black pepper", "peppercorn", "peppercorns"],
    "cumin": ["cumin"],
    "paprika": ["paprika"],
    "chili powder": ["chili powder", "chilli powder"],
    "cayenne": ["cayenne"],
    "cinnamon": ["cinnamon"],
    "nutmeg": ["nutmeg"],
    "clove": ["clove", "cloves"],
    "coriander": ["coriander"],
    "turmeric": ["turmeric"],
    "ginger": ["ginger"],
    "mustard": ["mustard", "mustard powder"],
    "cardamom": ["cardamom"],
    "allspice": ["allspice"],
    "smoked paprika": ["smoked paprika"],
}

DAIRY_TERMS: dict[str, list[str]] = {
    "milk": ["milk"],
    "cream": ["cream", "heavy cream", "whipping cream"],
    "butter": ["butter"],
    "cheese": ["cheese", "parmesan", "cheddar", "mozzarella", "feta", "goat cheese"],
    "yogurt": ["yogurt", "yoghurt"],
    "sour cream": ["sour cream"],
    "buttermilk": ["buttermilk"],
    "ricotta": ["ricotta"],
    "cream cheese": ["cream cheese"],
}

GRAIN_TERMS: dict[str, list[str]] = {
    "rice": ["rice"],
    "pasta": ["pasta", "spaghetti", "penne", "rigatoni", "macaroni", "noodles"],
    "bread": ["bread", "breadcrumbs", "bread crumbs"],
    "flour": ["flour"],
    "oats": ["oat", "oats", "oatmeal"],
    "cornmeal": ["cornmeal", "polenta", "grits"],
    "quinoa": ["quinoa"],
    "barley": ["barley"],
}

LEGUME_TERMS: dict[str, list[str]] = {
    "beans": ["bean", "beans", "black beans", "pinto", "kidney beans", "navy beans"],
    "lentils": ["lentil", "lentils"],
    "chickpeas": ["chickpea", "chickpeas", "garbanzo", "garbanzos"],
    "peas": ["pea", "peas", "split pea", "split peas"],
    "soy": ["soy", "soybean", "soybeans", "edamame"],
}

FRUIT_TERMS: dict[str, list[str]] = {
    "lemon": ["lemon", "lemons"],
    "lime": ["lime", "limes"],
    "orange": ["orange", "oranges"],
    "apple": ["apple", "apples"],
    "berry": ["berry", "berries", "strawberry", "strawberries", "blueberry", "blueberries"],
    "tomato": ["tomato", "tomatoes"],
    "avocado": ["avocado", "avocados"],
}

SWEETENER_TERMS: dict[str, list[str]] = {
    "sugar": ["sugar", "brown sugar", "granulated sugar"],
    "honey": ["honey"],
    "maple syrup": ["maple syrup"],
    "molasses": ["molasses"],
    "agave": ["agave", "agave syrup"],
}

OIL_FAT_TERMS: dict[str, list[str]] = {
    "olive oil": ["olive oil"],
    "vegetable oil": ["vegetable oil"],
    "canola oil": ["canola oil"],
    "coconut oil": ["coconut oil"],
    "sesame oil": ["sesame oil"],
    "lard": ["lard"],
    "shortening": ["shortening"],
    "ghee": ["ghee"],
}

TECHNIQUE_TERMS: dict[str, list[str]] = {
    "saute": ["saute", "sauteing", "sauté", "sautéing"],
    "braise": ["braise", "braising"],
    "poach": ["poach", "poaching"],
    "blanch": ["blanch", "blanching"],
    "marinate": ["marinate", "marinating"],
    "brine": ["brine", "brining"],
    "rest": ["rest", "resting"],
    "deglaze": ["deglaze", "deglazing"],
    "caramelize": ["caramelize", "caramelizing"],
    "emulsify": ["emulsify", "emulsifying"],
    "fold": ["fold", "folding"],
    "whisk": ["whisk", "whisking"],
    "knead": ["knead", "kneading"],
    "proof": ["proof", "proofing"],
    "temper": ["temper", "tempering"],
    "toast": ["toast", "toasting"],
    "debone": ["debone", "deboning"],
    "fillet": ["fillet", "filleting"],
    "cut": ["cut", "cutting"],
    "slice": ["slice", "slicing"],
    "dice": ["dice", "dicing"],
    "mince": ["mince", "mincing"],
    "chop": ["chop", "chopping"],
    "prep": ["prep", "prepping", "prepare", "preparing"],
}

COOKING_METHOD_TERMS: dict[str, list[str]] = {
    "sear": ["sear", "searing"],
    "roast": ["roast", "roasting"],
    "bake": ["bake", "baking"],
    "boil": ["boil", "boiling"],
    "simmer": ["simmer", "simmering"],
    "grill": ["grill", "grilling"],
    "fry": ["fry", "frying"],
    "deep fry": ["deep fry", "deep-fry", "deep frying"],
    "shallow fry": ["shallow fry", "pan fry", "pan-fry"],
    "steam": ["steam", "steaming"],
    "broil": ["broil", "broiling"],
    "stew": ["stew", "stewing"],
    "slow cook": ["slow cook", "slow-cook", "slow cooking"],
    "pressure cook": ["pressure cook", "pressure cooking"],
    "sous vide": ["sous vide"],
    "braise": ["braise", "braising"],
    "poach": ["poach", "poaching"],
    "saute": ["saute", "sauteing", "sauté", "sautéing"],
    "reduce": ["reduce", "reducing", "reduction"],
}

TOOL_TERMS: dict[str, list[str]] = {
    "skillet": ["skillet", "frying pan", "fry pan"],
    "nonstick pan": ["nonstick pan", "non-stick pan", "nonstick skillet", "non-stick skillet"],
    "saucepan": ["saucepan"],
    "pot": ["pot", "stockpot"],
    "dutch oven": ["dutch oven"],
    "sheet pan": ["sheet pan", "sheet tray"],
    "baking sheet": ["baking sheet"],
    "baking dish": ["baking dish", "casserole dish"],
    "cast iron": ["cast iron", "cast-iron", "cast iron pan", "cast-iron pan", "cast iron skillet"],
    "oven": ["oven"],
    "grill": ["grill", "grill pan"],
    "thermometer": ["thermometer", "probe"],
    "knife": ["knife", "chef's knife", "paring knife"],
    "cutting board": ["cutting board"],
    "bench scraper": ["bench scraper", "dough scraper"],
    "blender": ["blender"],
    "food processor": ["food processor"],
    "whisk": ["whisk"],
    "spatula": ["spatula"],
    "tongs": ["tongs"],
    "salad spinner": ["salad spinner"],
    "mixing bowl": ["mixing bowl"],
    "bowl": ["bowl"],
    "stand mixer": ["stand mixer"],
    "hand mixer": ["hand mixer"],
    "microwave": ["microwave"],
    "pressure cooker": ["pressure cooker", "instant pot"],
    "slow cooker": ["slow cooker", "crockpot"],
    "air fryer": ["air fryer"],
    "wok": ["wok"],
    "griddle": ["griddle"],
    "strainer": ["strainer", "sieve", "colander"],
}
