"""Render a static HTML dashboard from :class:`DashboardData`.

Writes four files into ``out_dir``:

* ``index.html``
* ``assets/dashboard_data.json``
* ``assets/dashboard.js``
* ``assets/style.css``

No external CDN dependencies – everything is local.
"""

from __future__ import annotations

import json
from pathlib import Path

from .dashboard_schema import DashboardData


def render_dashboard(out_dir: Path, data: DashboardData) -> Path:
    """Write dashboard files and return the path to ``index.html``."""
    out_dir.mkdir(parents=True, exist_ok=True)
    assets_dir = out_dir / "assets"
    assets_dir.mkdir(exist_ok=True)

    data_json = data.model_dump_json(indent=2)

    # Write data JSON
    data_path = assets_dir / "dashboard_data.json"
    data_path.write_text(
        data_json,
        encoding="utf-8",
    )

    # Write CSS
    css_path = assets_dir / "style.css"
    css_path.write_text(_CSS, encoding="utf-8")

    # Write JS
    js_path = assets_dir / "dashboard.js"
    js_path.write_text(_JS, encoding="utf-8")

    # Write HTML
    html_path = out_dir / "index.html"
    html_data_json = data_json.replace("</", "<\\/")
    html_path.write_text(
        _HTML.replace("__DASHBOARD_DATA_INLINE__", html_data_json),
        encoding="utf-8",
    )

    return html_path


# ---------------------------------------------------------------------------
# Static assets (inlined as Python strings to keep everything in one module)
# ---------------------------------------------------------------------------

_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>cookimport – Lifetime Stats Dashboard</title>
<link rel="stylesheet" href="assets/style.css">
</head>
<body>
<header id="dash-header">
  <h1>cookimport Stats Dashboard</h1>
  <div id="header-meta"></div>
</header>

<nav id="filters">
  <fieldset id="category-filters"><legend>Categories</legend></fieldset>
  <fieldset id="extractor-filters"><legend>EPUB Extractor</legend></fieldset>
  <fieldset id="date-filters"><legend>Date range</legend>
    <button data-days="7">7d</button>
    <button data-days="30">30d</button>
    <button data-days="90">90d</button>
    <button data-days="0" class="active">All</button>
  </fieldset>
</nav>

<main>
  <section id="throughput-section">
    <h2>Stage / Import Throughput</h2>
    <p class="section-note">Use the run/date view for overall history, then use file trend to see how one file's speed changes across runs.</p>
    <h3>Run / Date Trend (sec/recipe)</h3>
    <div id="throughput-chart" class="chart-container"></div>
    <h3>Recent Runs (Date / Run View)</h3>
    <table id="recent-runs"><thead><tr>
      <th>Timestamp</th><th>File</th><th>Importer</th><th>Total (s)</th>
      <th>Recipes</th><th>sec/recipe</th><th>EPUB Req</th><th>EPUB Eff</th><th>Auto Score</th><th>Run Config</th><th>Artifact</th>
    </tr></thead><tbody></tbody></table>
    <h3>File Trend (Selected File)</h3>
    <div class="inline-controls">
      <label for="file-trend-select">File:</label>
      <select id="file-trend-select"></select>
    </div>
    <div id="file-trend-chart" class="chart-container"></div>
    <table id="file-trend-table"><thead><tr>
      <th>Timestamp</th><th>Total (s)</th><th>sec/recipe</th><th>Recipes</th><th>Importer</th><th>EPUB Req</th><th>EPUB Eff</th><th>Auto Score</th><th>Run Config</th><th>Artifact</th>
    </tr></thead><tbody></tbody></table>
  </section>

  <section id="benchmark-section">
    <h2>Benchmark Evaluations</h2>
    <p class="section-note">Precision: how many predictions were correct. Recall: how much of the labeled gold set was recovered.</p>
    <div id="benchmark-chart" class="chart-container"></div>
    <h3>Recent Benchmarks</h3>
    <table id="benchmark-table"><thead><tr>
      <th>Timestamp</th><th>Precision</th><th>Recall</th><th>F1</th>
      <th>Gold</th><th>Matched</th><th>Recipes</th><th>Source</th><th>Importer</th><th>Run Config</th><th>Artifact</th>
    </tr></thead><tbody></tbody></table>
  </section>

  <section id="per-label-section">
    <h2>Per-Label Breakdown (Latest Benchmark)</h2>
    <table id="per-label-table"><thead><tr>
      <th>Label</th><th>Precision</th><th>Recall</th>
      <th>Gold</th><th>Pred</th>
    </tr></thead><tbody></tbody></table>
  </section>

  <section id="boundary-section">
    <h2>Boundary Classification (Latest Benchmark)</h2>
    <div id="boundary-summary"></div>
  </section>
</main>

<footer>Generated by <code>cookimport stats-dashboard</code></footer>

<script id="dashboard-data-inline" type="application/json">__DASHBOARD_DATA_INLINE__</script>
<script src="assets/dashboard.js"></script>
</body>
</html>
"""

_CSS = """\
:root {
  --bg: #f8f9fa;
  --card: #ffffff;
  --border: #dee2e6;
  --accent: #0d6efd;
  --accent2: #198754;
  --accent3: #dc3545;
  --text: #212529;
  --muted: #6c757d;
  --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --mono: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
}
*, *::before, *::after { box-sizing: border-box; }
body {
  font-family: var(--font); color: var(--text); background: var(--bg);
  margin: 0; padding: 0 1rem 2rem;
  line-height: 1.5;
}
header { padding: 1.5rem 0 0.5rem; border-bottom: 2px solid var(--border); margin-bottom: 1rem; }
header h1 { margin: 0 0 0.25rem; font-size: 1.5rem; }
#header-meta { font-size: 0.85rem; color: var(--muted); }
#header-meta span { margin-right: 1.5em; }

nav#filters { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
fieldset { border: 1px solid var(--border); border-radius: 6px; padding: 0.4rem 0.75rem; }
legend { font-size: 0.8rem; color: var(--muted); padding: 0 0.3rem; }
fieldset label { margin-right: 0.75rem; font-size: 0.85rem; cursor: pointer; }
fieldset button {
  background: var(--card); border: 1px solid var(--border); border-radius: 4px;
  padding: 0.2rem 0.6rem; margin-right: 0.3rem; cursor: pointer; font-size: 0.8rem;
}
fieldset button.active { background: var(--accent); color: #fff; border-color: var(--accent); }

section { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
  padding: 1.25rem; margin-bottom: 1.5rem; }
section h2 { margin: 0 0 1rem; font-size: 1.2rem; }
section h3 { margin: 1.25rem 0 0.5rem; font-size: 1rem; color: var(--muted); }
.section-note { margin: 0 0 0.75rem; color: var(--muted); font-size: 0.85rem; }

.chart-container { width: 100%; overflow-x: auto; min-height: 120px; }
.chart-container svg { display: block; }

table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid var(--border); }
th { font-weight: 600; color: var(--muted); font-size: 0.8rem; text-transform: uppercase; }
td.num { text-align: right; font-family: var(--mono); }
td a { color: var(--accent); text-decoration: none; word-break: break-all; }
td a:hover { text-decoration: underline; }
td.warn-note { color: #b45309; font-weight: 600; }

.inline-controls {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 0.25rem 0 0.75rem;
}
.inline-controls label {
  color: var(--muted);
  font-size: 0.85rem;
}
.inline-controls select {
  min-width: 240px;
  max-width: 100%;
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 0.25rem 0.4rem;
  background: var(--card);
  color: var(--text);
}

.empty-note { color: var(--muted); font-style: italic; padding: 1rem 0; }

footer { text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 2rem; }
"""

_JS = """\
(function () {
  "use strict";

  let DATA = null;
  let activeCategories = new Set(["stage_import", "benchmark_eval"]);
  let activeExtractors = new Set();
  let activeDays = 0; // 0 = all
  let selectedFileTrend = "";

  // ---- Load data ----
  function showLoadError(msg) {
    document.querySelector("main").innerHTML =
      '<p class="empty-note">' + msg + "</p>";
  }

  function loadInlineData() {
    const inline = document.getElementById("dashboard-data-inline");
    if (!inline) return null;
    const raw = (inline.textContent || "").trim();
    if (!raw) return null;
    return JSON.parse(raw);
  }

  function loadFromFetch(previousError) {
    fetch("assets/dashboard_data.json")
      .then(r => {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      })
      .then(d => { DATA = d; init(); })
      .catch(e => {
        if (previousError) {
          showLoadError("Failed to load dashboard data: " + previousError + "; " + e);
          return;
        }
        showLoadError("Failed to load dashboard_data.json: " + e);
      });
  }

  try {
    const inlineData = loadInlineData();
    if (inlineData) {
      DATA = inlineData;
      init();
    } else {
      loadFromFetch(null);
    }
  } catch (e) {
    loadFromFetch(e);
  }

  function init() {
    renderHeader();
    setupFilters();
    setupExtractorFilters();
    renderAll();
  }

  // ---- Header ----
  function renderHeader() {
    const m = document.getElementById("header-meta");
    const s = DATA.summary;
    const parts = [];
    parts.push("<span>Generated: " + DATA.generated_at.replace("T", " ").slice(0, 19) + "</span>");
    parts.push("<span>Stage records: " + s.total_stage_records + "</span>");
    parts.push("<span>Benchmark records: " + s.total_benchmark_records + "</span>");
    parts.push("<span>Total recipes: " + s.total_recipes + "</span>");
    if (s.total_runtime_seconds != null)
      parts.push("<span>Total runtime: " + s.total_runtime_seconds.toFixed(1) + "s</span>");
    m.innerHTML = parts.join("");
  }

  // ---- Filters ----
  function setupFilters() {
    const cf = document.getElementById("category-filters");
    const cats = [
      ["stage_import", "Stage imports", true],
      ["benchmark_eval", "Benchmarks", true],
      ["labelstudio_import", "Label Studio imports", false],
      ["benchmark_prediction", "Benchmark predictions", false],
    ];
    cats.forEach(([val, lbl, checked]) => {
      const id = "cat-" + val;
      const label = document.createElement("label");
      const cb = document.createElement("input");
      cb.type = "checkbox"; cb.checked = checked; cb.value = val; cb.id = id;
      if (checked) activeCategories.add(val);
      cb.addEventListener("change", () => {
        if (cb.checked) activeCategories.add(val); else activeCategories.delete(val);
        renderAll();
      });
      label.appendChild(cb);
      label.appendChild(document.createTextNode(" " + lbl));
      cf.appendChild(label);
    });

    document.querySelectorAll("#date-filters button").forEach(btn => {
      btn.addEventListener("click", () => {
        document.querySelectorAll("#date-filters button").forEach(b => b.classList.remove("active"));
        btn.classList.add("active");
        activeDays = parseInt(btn.dataset.days, 10);
        renderAll();
      });
    });
  }

  function setupExtractorFilters() {
    const ef = document.getElementById("extractor-filters");
    if (!ef) return;
    ef.innerHTML = "";
    const extractors = Array.from(
      new Set(
        (DATA.stage_records || [])
          .map(record => epubExtractorEffective(record) || epubExtractorRequested(record))
          .filter(Boolean)
      )
    ).sort((a, b) => a.localeCompare(b));

    activeExtractors = new Set(extractors);
    if (extractors.length === 0) {
      const note = document.createElement("span");
      note.className = "empty-note";
      note.textContent = "No EPUB extractor data";
      ef.appendChild(note);
      return;
    }

    extractors.forEach(extractor => {
      const id = "extractor-" + extractor;
      const label = document.createElement("label");
      const cb = document.createElement("input");
      cb.type = "checkbox";
      cb.checked = true;
      cb.value = extractor;
      cb.id = id;
      cb.addEventListener("change", () => {
        if (cb.checked) activeExtractors.add(extractor);
        else activeExtractors.delete(extractor);
        renderAll();
      });
      label.appendChild(cb);
      label.appendChild(document.createTextNode(" " + extractor));
      ef.appendChild(label);
    });
  }

  // ---- Filtering helpers ----
  function parseTs(ts) {
    if (ts == null) return null;
    const text = String(ts).trim();
    if (!text) return null;

    // Parse canonical timestamp forms explicitly to avoid browser Date.parse quirks:
    // YYYY-MM-DD_HH.MM.SS and YYYY-MM-DDTHH:MM:SS
    const m = text.match(/^(\\d{4})-(\\d{2})-(\\d{2})[T_](\\d{2})[.:](\\d{2})[.:](\\d{2})$/);
    if (m) {
      const d = new Date(
        Number(m[1]),
        Number(m[2]) - 1,
        Number(m[3]),
        Number(m[4]),
        Number(m[5]),
        Number(m[6]),
      );
      return isNaN(d.getTime()) ? null : d;
    }

    // Fallback for ISO strings with timezone offsets.
    const normalized = text.replace(/_(\\d{2})[.:](\\d{2})[.:](\\d{2})$/, "T$1:$2:$3");
    const d = new Date(normalized);
    return isNaN(d.getTime()) ? null : d;
  }

  function compareRunTimestampAsc(aTs, bTs) {
    const a = parseTs(aTs);
    const b = parseTs(bTs);
    if (a && b) return a - b;
    if (a) return -1;
    if (b) return 1;
    return (aTs || "").localeCompare(bTs || "");
  }

  function compareRunTimestampDesc(aTs, bTs) {
    return compareRunTimestampAsc(bTs, aTs);
  }

  function isRecent(ts) {
    if (activeDays === 0) return true;
    const d = parseTs(ts);
    if (!d) return true;
    const cutoff = new Date(Date.now() - activeDays * 86400000);
    return d >= cutoff;
  }

  function filteredStage() {
    return DATA.stage_records.filter(r =>
      activeCategories.has(r.run_category) &&
      isRecent(r.run_timestamp) &&
      stagePassesExtractorFilter(r)
    );
  }

  function filteredBenchmarks() {
    return DATA.benchmark_records.filter(r =>
      activeCategories.has(r.run_category) && isRecent(r.run_timestamp)
    );
  }

  function stagePassesExtractorFilter(record) {
    const extractor = epubExtractorEffective(record) || epubExtractorRequested(record);
    if (!extractor) return true;
    if (activeExtractors.size === 0) return false;
    return activeExtractors.has(extractor);
  }

  // ---- Render all sections ----
  function renderAll() {
    renderThroughput();
    renderBenchmarks();
    renderPerLabel();
    renderBoundary();
  }

  // ---- SVG sparkline helper ----
  function svgSparkline(points, opts) {
    // points: [{x: date, y: number, label: string}]
    // opts: {width, height, color, yLabel}
    const w = opts.width || 700;
    const h = opts.height || 140;
    const pad = { top: 20, right: 20, bottom: 30, left: 55 };
    const iw = w - pad.left - pad.right;
    const ih = h - pad.top - pad.bottom;

    if (points.length === 0) return '<p class="empty-note">No data points for chart.</p>';

    const xs = points.map(p => p.x.getTime());
    const ys = points.map(p => p.y);
    const xMin = Math.min(...xs), xMax = Math.max(...xs);
    const yMin = Math.min(0, Math.min(...ys)), yMax = Math.max(...ys) * 1.1 || 1;

    function sx(v) { return pad.left + (xMax === xMin ? iw / 2 : (v - xMin) / (xMax - xMin) * iw); }
    function sy(v) { return pad.top + ih - (yMax === yMin ? ih / 2 : (v - yMin) / (yMax - yMin) * ih); }

    let svg = '<svg width="' + w + '" height="' + h + '" xmlns="http://www.w3.org/2000/svg">';

    // Y-axis labels
    const yTicks = 4;
    for (let i = 0; i <= yTicks; i++) {
      const v = yMin + (yMax - yMin) * i / yTicks;
      const y = sy(v);
      svg += '<line x1="' + pad.left + '" y1="' + y + '" x2="' + (w - pad.right) + '" y2="' + y + '" stroke="#e9ecef" stroke-width="1"/>';
      svg += '<text x="' + (pad.left - 5) + '" y="' + (y + 4) + '" text-anchor="end" font-size="10" fill="#6c757d">' + v.toFixed(2) + '</text>';
    }

    // Y-axis label
    if (opts.yLabel) {
      svg += '<text x="12" y="' + (pad.top + ih / 2) + '" text-anchor="middle" font-size="11" fill="#6c757d" transform="rotate(-90, 12, ' + (pad.top + ih / 2) + ')">' + opts.yLabel + '</text>';
    }

    // Data line
    const linePoints = points.map(p => sx(p.x.getTime()) + "," + sy(p.y)).join(" ");
    svg += '<polyline fill="none" stroke="' + (opts.color || "#0d6efd") + '" stroke-width="2" points="' + linePoints + '"/>';

    // Data points
    points.forEach(p => {
      const cx = sx(p.x.getTime()), cy = sy(p.y);
      svg += '<circle cx="' + cx + '" cy="' + cy + '" r="3" fill="' + (opts.color || "#0d6efd") + '">';
      svg += '<title>' + p.label + '</title></circle>';
    });

    svg += '</svg>';
    return svg;
  }

  // ---- Throughput section ----
  function renderThroughput() {
    const records = filteredStage();
    const section = document.getElementById("throughput-section");
    if (records.length === 0) {
      section.innerHTML = '<h2>Stage / Import Throughput</h2><p class="empty-note">No stage/import records found. Run <code>cookimport perf-report</code> to generate performance history.</p>';
      return;
    }

    // Chart: sec/recipe over time
    const chartDiv = document.getElementById("throughput-chart");
    const points = records
      .filter(r => r.per_recipe_seconds != null && r.run_timestamp)
      .map(r => ({
        x: parseTs(r.run_timestamp) || new Date(),
        y: r.per_recipe_seconds,
        label: r.file_name + ": " + r.per_recipe_seconds.toFixed(3) + " sec/recipe"
      }))
      .filter(p => p.x)
      .sort((a, b) => a.x - b.x);

    chartDiv.innerHTML = svgSparkline(points, {
      width: Math.min(900, Math.max(400, points.length * 30)),
      height: 160,
      color: "#0d6efd",
      yLabel: "sec / recipe"
    });

    // Recent runs table
    const recentBody = document.querySelector("#recent-runs tbody");
    recentBody.innerHTML = "";
    const recentRuns = [...records]
      .sort((a, b) => compareRunTimestampDesc(a.run_timestamp, b.run_timestamp))
      .slice(0, 20);
    recentRuns.forEach(r => {
      const tr = document.createElement("tr");
      tr.innerHTML =
        '<td>' + esc(r.run_timestamp || "") + '</td>' +
        '<td>' + esc(r.file_name) + '</td>' +
        '<td>' + esc(r.importer_name || "-") + '</td>' +
        '<td class="num">' + (r.total_seconds != null ? r.total_seconds.toFixed(2) : "-") + '</td>' +
        '<td class="num">' + (r.recipes != null ? r.recipes : "-") + '</td>' +
        '<td class="num">' + (r.per_recipe_seconds != null ? r.per_recipe_seconds.toFixed(3) : "-") + '</td>' +
        extractorCells(r) +
        autoScoreCell(r) +
        runConfigCell(r) +
        '<td><a href="' + esc(r.artifact_dir || "") + '">' + esc(shortPath(r.artifact_dir)) + '</a></td>';
      recentBody.appendChild(tr);
    });

    // File trend controls
    const fileSelect = document.getElementById("file-trend-select");
    const fileNames = Array.from(new Set(records.map(r => r.file_name).filter(Boolean)))
      .sort((a, b) => a.localeCompare(b));

    if (!fileNames.includes(selectedFileTrend)) {
      selectedFileTrend = fileNames[0] || "";
    }

    const nextOptions = fileNames.map(name =>
      '<option value="' + esc(name) + '"' + (name === selectedFileTrend ? " selected" : "") + '>' + esc(name) + "</option>"
    ).join("");
    if (fileSelect.innerHTML !== nextOptions) {
      fileSelect.innerHTML = nextOptions;
    }

    if (!fileSelect.dataset.bound) {
      fileSelect.addEventListener("change", () => {
        selectedFileTrend = fileSelect.value;
        renderThroughput();
      });
      fileSelect.dataset.bound = "1";
    }

    const fileRecords = records
      .filter(r => r.file_name === selectedFileTrend)
      .sort((a, b) => compareRunTimestampAsc(a.run_timestamp, b.run_timestamp));

    const filePoints = fileRecords
      .filter(r => r.total_seconds != null && r.run_timestamp)
      .map(r => ({
        x: parseTs(r.run_timestamp) || new Date(),
        y: r.total_seconds,
        label: (r.run_timestamp || "") + " " + selectedFileTrend + " total=" + r.total_seconds.toFixed(3) + "s"
      }))
      .sort((a, b) => a.x - b.x);

    const fileChart = document.getElementById("file-trend-chart");
    fileChart.innerHTML = svgSparkline(filePoints, {
      width: Math.min(900, Math.max(400, filePoints.length * 55)),
      height: 160,
      color: "#198754",
      yLabel: "total sec"
    });

    const fileBody = document.querySelector("#file-trend-table tbody");
    fileBody.innerHTML = "";
    [...fileRecords]
      .sort((a, b) => compareRunTimestampDesc(a.run_timestamp, b.run_timestamp))
      .forEach(r => {
      const tr = document.createElement("tr");
      tr.innerHTML =
        '<td>' + esc(r.run_timestamp || "") + '</td>' +
        '<td class="num">' + (r.total_seconds != null ? r.total_seconds.toFixed(2) : "-") + '</td>' +
        '<td class="num">' + (r.per_recipe_seconds != null ? r.per_recipe_seconds.toFixed(3) : "-") + '</td>' +
        '<td class="num">' + (r.recipes != null ? r.recipes : "-") + '</td>' +
        '<td>' + esc(r.importer_name || "-") + '</td>' +
        extractorCells(r) +
        autoScoreCell(r) +
        runConfigCell(r) +
        '<td><a href="' + esc(r.artifact_dir || "") + '">' + esc(shortPath(r.artifact_dir)) + '</a></td>';
      fileBody.appendChild(tr);
    });
  }

  // ---- Benchmark section ----
  function renderBenchmarks() {
    const records = filteredBenchmarks();
    const section = document.getElementById("benchmark-section");
    if (records.length === 0) {
      section.innerHTML = '<h2>Benchmark Evaluations</h2><p class="empty-note">No benchmark evaluation records found. Run an eval workflow to generate eval_report.json files.</p>';
      return;
    }

    // Chart: recall + precision over time
    const chartDiv = document.getElementById("benchmark-chart");
    const rPoints = records
      .filter(r => r.recall != null && r.run_timestamp)
      .map(r => ({
        x: parseTs(r.run_timestamp) || new Date(),
        y: r.recall,
        label: (r.run_timestamp || "") + " recall=" + (r.recall != null ? r.recall.toFixed(4) : "?")
      }))
      .sort((a, b) => a.x - b.x);

    const pPoints = records
      .filter(r => r.precision != null && r.run_timestamp)
      .map(r => ({
        x: parseTs(r.run_timestamp) || new Date(),
        y: r.precision,
        label: (r.run_timestamp || "") + " precision=" + (r.precision != null ? r.precision.toFixed(4) : "?")
      }))
      .sort((a, b) => a.x - b.x);

    // Build dual-line SVG
    let chartHtml = "";
    if (rPoints.length > 0) {
      chartHtml += '<div style="margin-bottom:4px"><strong style="color:#198754;font-size:0.8rem">&#9679; Recall</strong> &nbsp; <strong style="color:#0d6efd;font-size:0.8rem">&#9679; Precision</strong></div>';
      // Merge for a common scale
      const allY = [...rPoints.map(p => p.y), ...pPoints.map(p => p.y)];
      const allX = [...rPoints.map(p => p.x.getTime()), ...pPoints.map(p => p.x.getTime())];
      const w = Math.min(900, Math.max(400, Math.max(rPoints.length, pPoints.length) * 40));

      chartHtml += svgSparkline(rPoints, {width: w, height: 160, color: "#198754", yLabel: "score"});
      // Overlay precision as second line (simpler: just render both)
      // For v1, show them stacked
      chartHtml += svgSparkline(pPoints, {width: w, height: 160, color: "#0d6efd", yLabel: "precision"});
    }
    chartDiv.innerHTML = chartHtml || '<p class="empty-note">Not enough data for trend chart.</p>';

    // Table
    const tbody = document.querySelector("#benchmark-table tbody");
    tbody.innerHTML = "";
    const sorted = [...records].sort((a, b) => compareRunTimestampDesc(a.run_timestamp, b.run_timestamp));
    sorted.forEach(r => {
      const sourceLabel = basename(r.source_file || "");
      const configSummary = runConfigSummary(r);
      const configRaw = r.run_config ? JSON.stringify(r.run_config) : "";
      const processedReportLink = r.processed_report_path
        ? ' <a href="' + esc(r.processed_report_path) + '" title="' + esc(r.processed_report_path) + '">report</a>'
        : "";
      const tr = document.createElement("tr");
      tr.innerHTML =
        '<td>' + esc(r.run_timestamp || "") + '</td>' +
        '<td class="num">' + fmt4(r.precision) + '</td>' +
        '<td class="num">' + fmt4(r.recall) + '</td>' +
        '<td class="num">' + fmt4(r.f1) + '</td>' +
        '<td class="num">' + (r.gold_total != null ? r.gold_total : "-") + '</td>' +
        '<td class="num">' + (r.gold_matched != null ? r.gold_matched : "-") + '</td>' +
        '<td class="num">' + (r.recipes != null ? r.recipes : "-") + '</td>' +
        '<td title="' + esc(r.source_file || "") + '">' + esc(sourceLabel || "-") + '</td>' +
        '<td>' + esc(r.importer_name || "-") + '</td>' +
        '<td title="' + esc(configRaw) + '">' + esc(configSummary || "-") + '</td>' +
        '<td><a href="' + esc(r.artifact_dir || "") + '">' + esc(shortPath(r.artifact_dir)) + '</a>' + processedReportLink + '</td>';
      tbody.appendChild(tr);
    });
  }

  // ---- Per-label section ----
  function renderPerLabel() {
    const records = filteredBenchmarks();
    const section = document.getElementById("per-label-section");
    if (records.length === 0) {
      section.innerHTML = '<h2>Per-Label Breakdown</h2><p class="empty-note">No benchmark records with per-label data.</p>';
      return;
    }
    // Use the most recent benchmark that has per_label data
    const sorted = [...records].sort((a, b) => compareRunTimestampDesc(a.run_timestamp, b.run_timestamp));
    const latest = sorted.find(r => r.per_label && r.per_label.length > 0);
    if (!latest) {
      section.innerHTML = '<h2>Per-Label Breakdown</h2><p class="empty-note">No per-label metrics available in benchmark records.</p>';
      return;
    }
    section.querySelector("h2").textContent = "Per-Label Breakdown (" + esc(latest.run_timestamp || "latest") + ")";
    const tbody = document.querySelector("#per-label-table tbody");
    tbody.innerHTML = "";
    latest.per_label.forEach(lbl => {
      const f1 = (lbl.precision != null && lbl.recall != null && (lbl.precision + lbl.recall) > 0)
        ? (2 * lbl.precision * lbl.recall / (lbl.precision + lbl.recall)) : null;
      const tr = document.createElement("tr");
      tr.innerHTML =
        '<td>' + esc(lbl.label) + '</td>' +
        '<td class="num">' + fmt4(lbl.precision) + '</td>' +
        '<td class="num">' + fmt4(lbl.recall) + '</td>' +
        '<td class="num">' + (lbl.gold_total != null ? lbl.gold_total : "-") + '</td>' +
        '<td class="num">' + (lbl.pred_total != null ? lbl.pred_total : "-") + '</td>';
      tbody.appendChild(tr);
    });
  }

  // ---- Boundary section ----
  function renderBoundary() {
    const records = filteredBenchmarks();
    const section = document.getElementById("boundary-section");
    if (records.length === 0) {
      section.innerHTML = '<h2>Boundary Classification</h2><p class="empty-note">No benchmark records.</p>';
      return;
    }
    const sorted = [...records].sort((a, b) => compareRunTimestampDesc(a.run_timestamp, b.run_timestamp));
    const latest = sorted.find(r => r.boundary_correct != null || r.boundary_over != null || r.boundary_under != null || r.boundary_partial != null);
    if (!latest) {
      section.innerHTML = '<h2>Boundary Classification</h2><p class="empty-note">No boundary data available in benchmark records.</p>';
      return;
    }
    section.querySelector("h2").textContent = "Boundary Classification (" + esc(latest.run_timestamp || "latest") + ")";
    const div = document.getElementById("boundary-summary");
    const total = (latest.boundary_correct || 0) + (latest.boundary_over || 0) + (latest.boundary_under || 0) + (latest.boundary_partial || 0);
    const pct = function(v) { return total > 0 ? ((v || 0) / total * 100).toFixed(1) + "%" : "-"; };
    div.innerHTML =
      '<table><thead><tr><th>Category</th><th>Count</th><th>%</th></tr></thead><tbody>' +
      '<tr><td>Correct</td><td class="num">' + (latest.boundary_correct != null ? latest.boundary_correct : "-") + '</td><td class="num">' + pct(latest.boundary_correct) + '</td></tr>' +
      '<tr><td>Over-segmented</td><td class="num">' + (latest.boundary_over != null ? latest.boundary_over : "-") + '</td><td class="num">' + pct(latest.boundary_over) + '</td></tr>' +
      '<tr><td>Under-segmented</td><td class="num">' + (latest.boundary_under != null ? latest.boundary_under : "-") + '</td><td class="num">' + pct(latest.boundary_under) + '</td></tr>' +
      '<tr><td>Partial</td><td class="num">' + (latest.boundary_partial != null ? latest.boundary_partial : "-") + '</td><td class="num">' + pct(latest.boundary_partial) + '</td></tr>' +
      '</tbody></table>';
  }

  // ---- Utils ----
  function esc(s) {
    if (!s) return "";
    return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  }
  function fmt4(v) { return v != null ? v.toFixed(4) : "-"; }
  function basename(path) {
    if (!path) return "";
    const parts = path.replace(/\\\\/g, "/").split("/");
    return parts[parts.length - 1] || path;
  }
  function epubExtractorRequested(record) {
    if (record.epub_extractor_requested) return String(record.epub_extractor_requested);
    const importer = String(record.importer_name || "").toLowerCase();
    if (importer && importer !== "epub") return null;
    const cfg = record.run_config || {};
    return cfg.epub_extractor_requested || cfg.epub_extractor || null;
  }
  function epubExtractorEffective(record) {
    if (record.epub_extractor_effective) return String(record.epub_extractor_effective);
    const importer = String(record.importer_name || "").toLowerCase();
    if (importer && importer !== "epub") return null;
    const cfg = record.run_config || {};
    return cfg.epub_extractor_effective || cfg.epub_extractor || null;
  }
  function autoScoreValue(record) {
    const direct = record.epub_auto_selected_score;
    if (direct != null && direct !== "") {
      const parsed = Number(direct);
      if (!Number.isNaN(parsed)) return parsed;
    }
    const cfg = record.run_config || {};
    const cfgValue = cfg.epub_auto_selected_score;
    if (cfgValue != null && cfgValue !== "") {
      const parsed = Number(cfgValue);
      if (!Number.isNaN(parsed)) return parsed;
    }
    return null;
  }
  function extractorCells(record) {
    return (
      '<td>' + esc(epubExtractorRequested(record) || "-") + '</td>' +
      '<td>' + esc(epubExtractorEffective(record) || "-") + '</td>'
    );
  }
  function autoScoreCell(record) {
    const score = autoScoreValue(record);
    return '<td class="num">' + (score != null ? score.toFixed(3) : "-") + '</td>';
  }
  function runConfigSummary(record) {
    if (record.run_config_summary) {
      return record.run_config_summary;
    }
    const cfg = record.run_config || {};
    const parts = [];
    if (cfg.epub_extractor != null) parts.push("epub_extractor=" + cfg.epub_extractor);
    if (cfg.epub_extractor_requested != null) parts.push("epub_extractor_requested=" + cfg.epub_extractor_requested);
    if (cfg.epub_extractor_effective != null) parts.push("epub_extractor_effective=" + cfg.epub_extractor_effective);
    if (cfg.ocr_device != null) parts.push("ocr_device=" + cfg.ocr_device);
    if (cfg.ocr_batch_size != null) parts.push("ocr_batch_size=" + cfg.ocr_batch_size);
    if (cfg.effective_workers != null) parts.push("effective_workers=" + cfg.effective_workers);
    else if (cfg.workers != null) parts.push("workers=" + cfg.workers);
    return parts.join(" | ");
  }
  function runConfigCell(record) {
    const summary = runConfigSummary(record);
    const warning = record.run_config_warning || "";
    const hash = record.run_config_hash || "";
    let title = warning;
    if (record.run_config) {
      title = JSON.stringify(record.run_config);
    } else if (summary) {
      title = summary;
    }
    if (hash) {
      title = (title ? title + "\\n" : "") + "hash=" + hash;
    }
    if (summary) {
      const shortHash = hash ? " [" + hash.slice(0, 10) + "]" : "";
      return '<td title="' + esc(title) + '">' + esc(summary + shortHash) + '</td>';
    }
    if (warning) {
      return '<td class="warn-note" title="' + esc(title) + '">' + esc("[warn] " + warning) + '</td>';
    }
    return '<td>-</td>';
  }
  function shortPath(p) {
    if (!p) return "";
    // Show last 3 path components
    const parts = p.replace(/\\\\/g, "/").split("/");
    return parts.slice(-3).join("/");
  }
})();
"""
