from __future__ import annotations

from cookimport.runs.stage_names import (
    LABEL_DETERMINISTIC_STAGE_KEY,
    LABEL_REFINE_STAGE_KEY,
    LINE_ROLE_STAGE_KEY,
    NONRECIPE_FINALIZE_STAGE_KEY,
    NONRECIPE_ROUTE_STAGE_KEY,
    RECIPE_BOUNDARY_STAGE_KEY,
    RECIPE_BUILD_FINAL_STAGE_KEY,
    RECIPE_BUILD_INTERMEDIATE_STAGE_KEY,
    RECIPE_REFINE_STAGE_KEY,
    WRITE_OUTPUTS_STAGE_KEY,
    stage_order,
)


def test_stage_order_uses_clean_dependency_slots() -> None:
    assert [
        (LINE_ROLE_STAGE_KEY, stage_order(LINE_ROLE_STAGE_KEY)),
        (LABEL_DETERMINISTIC_STAGE_KEY, stage_order(LABEL_DETERMINISTIC_STAGE_KEY)),
        (LABEL_REFINE_STAGE_KEY, stage_order(LABEL_REFINE_STAGE_KEY)),
        (RECIPE_BOUNDARY_STAGE_KEY, stage_order(RECIPE_BOUNDARY_STAGE_KEY)),
        (
            RECIPE_BUILD_INTERMEDIATE_STAGE_KEY,
            stage_order(RECIPE_BUILD_INTERMEDIATE_STAGE_KEY),
        ),
        (RECIPE_REFINE_STAGE_KEY, stage_order(RECIPE_REFINE_STAGE_KEY)),
        (RECIPE_BUILD_FINAL_STAGE_KEY, stage_order(RECIPE_BUILD_FINAL_STAGE_KEY)),
        (NONRECIPE_ROUTE_STAGE_KEY, stage_order(NONRECIPE_ROUTE_STAGE_KEY)),
        (NONRECIPE_FINALIZE_STAGE_KEY, stage_order(NONRECIPE_FINALIZE_STAGE_KEY)),
        (WRITE_OUTPUTS_STAGE_KEY, stage_order(WRITE_OUTPUTS_STAGE_KEY)),
    ] == [
        (LINE_ROLE_STAGE_KEY, 10),
        (LABEL_DETERMINISTIC_STAGE_KEY, 20),
        (LABEL_REFINE_STAGE_KEY, 30),
        (RECIPE_BOUNDARY_STAGE_KEY, 40),
        (RECIPE_BUILD_INTERMEDIATE_STAGE_KEY, 50),
        (RECIPE_REFINE_STAGE_KEY, 60),
        (RECIPE_BUILD_FINAL_STAGE_KEY, 70),
        (NONRECIPE_ROUTE_STAGE_KEY, 80),
        (NONRECIPE_FINALIZE_STAGE_KEY, 90),
        (WRITE_OUTPUTS_STAGE_KEY, 100),
    ]
