from __future__ import annotations


LABEL_DETERMINISTIC_DIR_NAME = "label_deterministic"
LABEL_REFINE_DIR_NAME = "label_refine"
RECIPE_BOUNDARY_DIR_NAME = "recipe_boundary"
LINE_ROLE_PIPELINE_DIR_NAME = "line-role-pipeline"

LABEL_DETERMINISTIC_SCHEMA_VERSION = "label_deterministic.v1"
LABEL_REFINE_SCHEMA_VERSION = "label_refine.v1"
RECIPE_BOUNDARY_SCHEMA_VERSION = "recipe_boundary.v1"
RECIPE_BOUNDARY_DECISIONS_SCHEMA_VERSION = "recipe_boundary_decisions.v1"
AUTHORITATIVE_BLOCK_LABELS_SCHEMA_VERSION = "authoritative_block_labels.v1"
LINE_ROLE_AUTHORITATIVE_BLOCK_LABELS_SCHEMA_VERSION = "line_role_authoritative_block_labels.v1"

LINE_ROLE_AUTHORITATIVE_LABELED_LINES_FILE_NAME = "authoritative_labeled_lines.jsonl"
LINE_ROLE_AUTHORITATIVE_BLOCK_LABELS_FILE_NAME = "authoritative_block_labels.json"
LINE_ROLE_LABEL_DIFFS_FILE_NAME = "label_diffs.jsonl"

NONRECIPE_ROW_ROUTE_FILE_NAME = "08_nonrecipe_row_route.json"
NONRECIPE_EXCLUSIONS_FILE_NAME = "08_nonrecipe_exclusions.jsonl"
NONRECIPE_ROW_AUTHORITY_FILE_NAME = "09_nonrecipe_row_authority.json"
NONRECIPE_KNOWLEDGE_GROUPS_FILE_NAME = "09_nonrecipe_knowledge_groups.json"
NONRECIPE_FINALIZE_STATUS_FILE_NAME = "09_nonrecipe_finalize_status.json"
RECIPE_ROW_OWNERSHIP_FILE_NAME = "recipe_row_ownership.json"
SEMANTIC_ROW_PREDICTIONS_FILE_NAME = "semantic_row_predictions.json"

NONRECIPE_ROW_ROUTE_SCHEMA_VERSION = "nonrecipe_row_route.v1"
NONRECIPE_ROW_AUTHORITY_SCHEMA_VERSION = "nonrecipe_row_authority.v1"
NONRECIPE_KNOWLEDGE_GROUPS_SCHEMA_VERSION = "nonrecipe_knowledge_groups.v1"
NONRECIPE_FINALIZE_STATUS_SCHEMA_VERSION = "nonrecipe_finalize_status.v1"
RECIPE_ROW_OWNERSHIP_SCHEMA_VERSION = "recipe_row_ownership.v1"

NONRECIPE_ROUTE_FIELD = "nonrecipe_route"
NONRECIPE_FINAL_CATEGORY_FIELD = "nonrecipe_final_category"
NONRECIPE_CANDIDATE_INPUT_MODE = "nonrecipe_candidate_spans"

# Compatibility aliases for older call sites that still import block-era names.
NONRECIPE_ROUTE_FILE_NAME = NONRECIPE_ROW_ROUTE_FILE_NAME
NONRECIPE_AUTHORITY_FILE_NAME = NONRECIPE_ROW_AUTHORITY_FILE_NAME
RECIPE_BLOCK_OWNERSHIP_FILE_NAME = RECIPE_ROW_OWNERSHIP_FILE_NAME
NONRECIPE_ROUTE_SCHEMA_VERSION = NONRECIPE_ROW_ROUTE_SCHEMA_VERSION
NONRECIPE_AUTHORITY_SCHEMA_VERSION = NONRECIPE_ROW_AUTHORITY_SCHEMA_VERSION
RECIPE_BLOCK_OWNERSHIP_SCHEMA_VERSION = RECIPE_ROW_OWNERSHIP_SCHEMA_VERSION
